### PR TITLE
Fix build and shrink repo

### LINKED ISSUE #9: tests don't work
Am I missing something? `libc-test` kept bailing because of syntax errors in `src/common/options.h`. I had to apply [this patch](http://repo.or.cz/libc-test.git/patch/bbe3b5ea6b0ca41b872a3a32d1b68d022faed0b6) to resolve the problem, but there are undefined symbols and references all over the place.

### PR DESCRIPTION
**Pull request by mrhota**
Travis fails because of some failure with spawn.exe and spawn-static.exe, but those tests pass on my machine. I wanted to get this PR together before trying to fix those two tests (if needed).

Fixes #9 

CC @dikaiosune

### CODE REVIEW

**Comment by mrhota** [comment]
I removed `libc-test` and `musl` from the repo and added them as submodules, hence the enormous amount of deleted files.

**Comment by mrhota** [comment]
@dikaiosune any idea why `spawn` tests would fail on travis? they pass locally...

**Comment by mrhota** [comment]
@dikaiosune ping

**Comment by anp** [comment]
Thanks! Looks great!

**Comment by anp** [comment]
One comment: might be a good idea to include submodule init instructions in the README.

**Pull request merged**
