### PR TITLE
Improved strlen

### PR DESCRIPTION
**Pull request by mrhota**
Straightforward C-to-Rust of musl's strlen.

### CODE REVIEW

**Comment by mrhota** [comment]
failure might be spurious? seems like it built on my repo just fine

UPDATE: cached version of `rustfmt` may cause `check_fmt.sh` to die. Looks like builder croaks right at the start.

**Comment by mrhota** [comment]
cc @dikaiosune

**Comment by anp** [comment]
I deleted the cache to get it to rebuild rustfmt and restarted the build.

**Comment by anp** [comment]
Oops! Sorry, it looks like I may have merged #15 in the wrong order. Let me know when this is good to merge or if I can help?

**Comment by mrhota** [comment]
@dikaiosune No problem. It looks like this is a clean build, so this is ready 2 rock

**Pull request merged**
